module.exports = {
  GOOGLE_CLIENTID: "",
  GOOGLE_CLIENTSECRET: "",
  GOOGLE_CALLBACKURL: "",
  FACEBOOK_CLIENTID: "",
  FACEBOOK_CLIENTSECRET: "",
  FACEBOOK_CALLBACKURL: "",
  NAVER_CLIENTID: "",
  NAVER_CLIENTSECRET: "",
  NAVER_CALLBACKURL: "",
  KAKAO_CLIENTID: "",
  KAKAO_CLIENTSECRET: "",
  KAKAO_CALLBACKURL: ""
};
